import { AlertTriangle, CheckCircle2, FileSearch, Scale } from 'lucide-react';
import type { ComplianceReport, RuleResult } from '../api/compliance';
import { EvidenceViewer } from './EvidenceViewer';
import { EmptyState, SectionHeader, StatusBadge } from './ui';

export function ComplianceResultsPanel({ reports, isAnalyzing }: { reports: ComplianceReport[]; isAnalyzing: boolean }) {
  if (isAnalyzing) return <section className="app-surface p-5"><div className="flex items-start gap-3"><FileSearch size={20} className="mt-0.5 animate-pulse text-[#8cc1ff]" /><div><p className="section-title">Evaluating compliance rules</p><p className="mt-1 text-sm leading-relaxed text-[var(--text-muted)]">Comparing extracted declarations against the configured legal-metrology rules.</p></div></div><div className="mt-4 h-1 overflow-hidden bg-[#1b2636]"><div className="h-full w-2/3 bg-[#5b8cff]" /></div></section>;
  if (!reports.length) return <EmptyState icon={<Scale size={28} />} title="Rule evaluation pending" description="Upload package evidence and run analysis to create an evidence-linked compliance assessment." />;
  return <div className="space-y-5">{reports.map((report, index) => <section key={report.image_id} className="app-surface overflow-hidden"><SectionHeader eyebrow={`Evidence assessment ${index + 1}`} title="Compliance findings" description={`${report.total_rules_checked} rules evaluated against extracted declarations.`} action={<StatusBadge value={report.overall_status} />} /><div className="grid border-b border-[var(--line)] grid-cols-4">{[{ label: 'Passed', value: report.passed_count, tone: 'text-[#73dfaa]' }, { label: 'Failed', value: report.failed_count, tone: 'text-[#ff9999]' }, { label: 'Review', value: report.review_count, tone: 'text-[#f3c973]' }, { label: 'Not applicable', value: report.not_applicable_count, tone: 'text-[var(--text-muted)]' }].map((metric) => <div key={metric.label} className="border-r border-[var(--line)] px-3 py-3 last:border-r-0"><p className="metric-label">{metric.label}</p><p className={`mt-1 font-mono text-lg font-semibold ${metric.tone}`}>{metric.value}</p></div>)}</div><div className="divide-y divide-[var(--line)]">{report.rule_results.map((result) => <RuleFinding key={result.rule_id} result={result} />)}</div></section>)}</div>;
}

function RuleFinding({ result }: { result: RuleResult }) {
  const isFailure = result.status === 'FAIL'; const Icon = isFailure ? AlertTriangle : result.status === 'PASS' ? CheckCircle2 : Scale;
  return <article className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><Icon size={19} className={`mt-0.5 shrink-0 ${isFailure ? 'text-[#ff9999]' : result.status === 'PASS' ? 'text-[#73dfaa]' : 'text-[#f3c973]'}`} /><div><div className="flex flex-wrap items-center gap-2"><p className="font-mono text-[11px] font-bold text-[#a9c7ff]">{result.rule_id}</p><span className="rounded border border-[var(--line-strong)] px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wide text-[var(--text-muted)]">{result.severity}</span></div><h4 className="mt-1 text-sm font-semibold text-[var(--text)]">{result.rule_name}</h4><p className="mt-1 text-sm leading-relaxed text-[var(--text-muted)]">{result.message}</p></div></div><StatusBadge value={result.status} /></div><div className="mt-4 grid gap-3 border-t border-[var(--line)] pt-4 lg:grid-cols-[1fr_1fr_.9fr]"><FindingValue label="Expected" value={result.expected} /><FindingValue label={result.field ? `Detected · ${result.field}` : 'Detected'} value={result.actual || 'Not detected'} /><div><p className="metric-label">Rule reference</p><p className="mt-1 text-xs leading-relaxed text-[var(--text-muted)]">{result.source_reference || 'Not provided'}</p></div></div>{result.evidence && <div className="mt-4"><EvidenceViewer evidence={result.evidence} /></div>}</article>;
}

function FindingValue({ label, value }: { label: string; value: string }) { return <div><p className="metric-label">{label}</p><p className="mt-1 break-words font-mono text-xs leading-relaxed text-[#dbe3ef]">{value}</p></div>; }
