import { useEffect, useRef } from 'react';
import { FileSearch, MapPin, Timer } from 'lucide-react';
import type { ImageAnalysisResult, OCRBlock } from '../api/analysis';
import { StatusBadge } from './ui';

function EvidenceImage({ imageUrl, blocks }: { imageUrl: string; blocks: OCRBlock[] }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const imageRef = useRef<HTMLImageElement>(null);
  useEffect(() => { const image = imageRef.current; const canvas = canvasRef.current; if (!image || !canvas) return; const draw = () => { const context = canvas.getContext('2d'); if (!context || !image.naturalWidth) return; const rect = image.getBoundingClientRect(); canvas.width = rect.width; canvas.height = rect.height; context.clearRect(0, 0, canvas.width, canvas.height); const sx = rect.width / image.naturalWidth; const sy = rect.height / image.naturalHeight; context.lineWidth = 1.5; context.font = '600 10px Inter, sans-serif'; blocks.forEach((block, index) => { const [x1, y1, x2, y2] = block.bbox; const x = x1 * sx; const y = y1 * sy; const width = (x2 - x1) * sx; const height = (y2 - y1) * sy; context.strokeStyle = '#62a8ff'; context.fillStyle = 'rgba(98, 168, 255, .09)'; context.fillRect(x, y, width, height); context.strokeRect(x, y, width, height); context.fillStyle = '#62a8ff'; context.fillRect(x, Math.max(0, y - 17), 25, 17); context.fillStyle = '#07111f'; context.fillText(String(index + 1), x + 8, Math.max(11, y - 5)); }); }; if (image.complete) draw(); else image.addEventListener('load', draw); const observer = new ResizeObserver(draw); observer.observe(image); return () => { image.removeEventListener('load', draw); observer.disconnect(); }; }, [blocks, imageUrl]);
  return <div className="relative overflow-hidden rounded-md border border-[var(--line)] bg-[#080d15]"><img ref={imageRef} src={imageUrl} alt="Inspection evidence with detected OCR regions" className="block max-h-[520px] w-full object-contain" /><canvas ref={canvasRef} className="pointer-events-none absolute inset-0 h-full w-full" /></div>;
}

export default function OCRResultsPanel({ imageUrl, result }: { imageUrl: string; result: ImageAnalysisResult }) {
  const blocks = result.ocr?.blocks || []; const average = blocks.length ? Math.round((blocks.reduce((sum, block) => sum + block.confidence, 0) / blocks.length) * 100) : null;
  if (result.status === 'NOT_ANALYSED') return <div className="app-panel flex min-h-64 flex-col items-center justify-center p-6 text-center"><FileSearch size={28} className="text-[var(--text-faint)]" /><p className="mt-3 text-sm font-semibold text-[var(--text)]">OCR pending</p><p className="mt-1 max-w-xs text-xs leading-relaxed text-[var(--text-muted)]">Run inspection analysis to detect declarations and map them to the source evidence.</p></div>;
  return <section className="app-surface overflow-hidden"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-[var(--line)] px-4 py-3"><div><p className="app-kicker">Evidence to OCR</p><h3 className="section-title mt-1">{result.status === 'OK' ? 'OCR complete' : 'OCR requires attention'}</h3></div><StatusBadge value={result.status === 'OK' ? 'COMPLETE' : 'ERROR'} /></header><div className="p-4"><EvidenceImage imageUrl={imageUrl} blocks={blocks} /></div><div className="grid border-y border-[var(--line)] sm:grid-cols-3"><div className="px-4 py-3"><p className="metric-label">Text regions</p><p className="mt-1 font-mono text-lg font-semibold text-[var(--text)]">{blocks.length}</p></div><div className="border-y border-[var(--line)] px-4 py-3 sm:border-x sm:border-y-0"><p className="metric-label">Average confidence</p><p className="mt-1 font-mono text-lg font-semibold text-[var(--text)]">{average === null ? '—' : `${average}%`}</p></div><div className="px-4 py-3"><p className="metric-label">Processing</p><p className="mt-1 flex items-center gap-1.5 font-mono text-xs text-[var(--text-muted)]"><Timer size={13} />{result.ocr?.processing_time_ms == null ? '—' : `${result.ocr.processing_time_ms} ms`}</p></div></div>{result.status === 'ERROR' ? <div className="p-4"><div className="ui-alert ui-alert-error">{result.error || 'OCR could not process this evidence.'}</div></div> : <div className="p-4"><div className="mb-3 flex items-center justify-between"><p className="app-kicker">Detected text</p>{result.quality && <StatusBadge value={result.quality.status === 'GOOD' ? 'COMPLETE' : result.quality.status === 'FAIR' ? 'REVIEW' : 'ERROR'} label={`Image quality · ${result.quality.status}`} />}</div>{blocks.length ? <ol className="max-h-72 space-y-2 overflow-y-auto pr-1">{blocks.map((block, index) => <li key={`${block.text}-${index}`} className="flex gap-3 rounded-md border border-[var(--line)] bg-[#0a0f18] px-3 py-2.5"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#17243c] font-mono text-[10px] font-bold text-[#a9c7ff]">{index + 1}</span><div className="min-w-0"><p className="break-words text-sm text-[#dde5f0]">{block.text}</p><p className="mt-1 flex items-center gap-2 font-mono text-[10px] text-[var(--text-faint)]"><span>{Math.round(block.confidence * 100)}% confidence</span><span className="inline-flex items-center gap-1"><MapPin size={11} />region recorded</span></p></div></li>)}</ol> : <p className="text-sm text-[var(--text-muted)]">No text was detected. Upload a clearer image and run analysis again.</p>}</div>}</section>;
}
