import { FileCheck2, Package } from 'lucide-react';
import type { ProductInfo } from '../api/product_info';
import { EmptyState, SectionHeader, StatusBadge } from './ui';

const fields: Record<string, { label: string; required: boolean }> = {
  product_name: { label: 'Product name', required: true }, brand_name: { label: 'Brand', required: true }, manufacturer: { label: 'Manufacturer', required: true }, net_quantity: { label: 'Net quantity', required: true }, mrp: { label: 'MRP', required: true }, manufacturing_date: { label: 'Manufacturing date', required: true }, expiry_date: { label: 'Expiry / best before', required: true }, batch_number: { label: 'Batch number', required: true }, country_of_origin: { label: 'Country of origin', required: true }, license_number: { label: 'FSSAI / licence no.', required: true }, ingredients: { label: 'Ingredients', required: false }, customer_care: { label: 'Customer care', required: false }, warnings: { label: 'Warnings / declarations', required: false },
};

export default function ProductInfoPanel({ productInfo }: { productInfo: ProductInfo | null }) {
  if (!productInfo) return <EmptyState icon={<Package size={26} />} title="Declarations pending" description="Structured package declarations will appear here after evidence analysis is complete." />;
  const fieldMap = Object.fromEntries(productInfo.fields.map((field) => [field.field_name, field]));
  const rows = Object.entries(fields).map(([key, meta]) => ({ key, meta, value: fieldMap[key] }));
  const detected = rows.filter((row) => row.value?.detection_status === 'DETECTED').length;
  return <section className="app-surface overflow-hidden"><SectionHeader eyebrow="Declaration extraction" title="Package declarations" description={`${detected} of ${rows.length} configured declarations detected from evidence.`} action={<FileCheck2 size={18} className="text-[var(--text-faint)]" />} /><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="border-b border-[var(--line)] bg-[var(--surface-raised)] text-[10px] font-bold uppercase tracking-[.11em] text-[var(--text-faint)]"><tr><th className="px-4 py-3">Declaration</th><th className="px-4 py-3">Detected value</th><th className="px-4 py-3">Evidence</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{rows.map(({ key, meta, value }) => <tr key={key}><td className="px-4 py-3 text-sm text-[var(--text-muted)]">{meta.label}{meta.required && <span className="ml-1 text-[var(--danger)]" aria-label="Required declaration">*</span>}</td><td className="max-w-[230px] px-4 py-3 text-sm font-medium text-[var(--text)]">{value?.value || <span className="text-[var(--text-faint)]">Not detected</span>}</td><td className="px-4 py-3 font-mono text-[11px] text-[var(--text-faint)]">{value?.evidence?.confidence == null ? '—' : `${Math.round(value.evidence.confidence * 100)}% confidence`}</td><td className="px-4 py-3"><StatusBadge value={value?.detection_status} /></td></tr>)}</tbody></table></div><p className="border-t border-[var(--line)] px-4 py-3 text-[11px] text-[var(--text-faint)]"><span className="mr-1 text-[var(--danger)]">*</span> Mandatory declaration under the configured rules.</p></section>;
}
