import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ChevronLeft, ChevronRight, ClipboardList, Filter, Image as ImageIcon, Plus, Search } from 'lucide-react';
import { getInspections, type InspectionListItem } from '../api/inspections';
import { Alert, EmptyState, LoadingState, StatusBadge } from '../components/ui';

export default function InspectionsPage() {
  const [inspections, setInspections] = useState<InspectionListItem[]>([]);
  const [totalCount, setTotalCount] = useState(0); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  const [searchInput, setSearchInput] = useState(''); const [appliedSearch, setAppliedSearch] = useState(''); const [complianceStatus, setComplianceStatus] = useState(''); const [page, setPage] = useState(1);
  const pageSize = 10;
  useEffect(() => { setLoading(true); setFailed(false); getInspections({ search: appliedSearch || undefined, compliance_status: complianceStatus || undefined, skip: (page - 1) * pageSize, limit: pageSize }).then((data) => { setInspections(data.items); setTotalCount(data.totalCount); }).catch(() => setFailed(true)).finally(() => setLoading(false)); }, [appliedSearch, complianceStatus, page]);
  const pages = Math.max(1, Math.ceil(totalCount / pageSize));
  const applySearch = (event: React.FormEvent) => { event.preventDefault(); setPage(1); setAppliedSearch(searchInput); };

  return <div className="space-y-6"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="app-kicker">Inspection register</p><h2 className="app-title mt-2">Every case, traceable.</h2><p className="app-subtitle mt-3">{totalCount} inspection{totalCount === 1 ? '' : 's'} in the current compliance workspace.</p></div><Link to="/inspections/new" className="ui-button-primary"><Plus size={16} /> New inspection</Link></section>
    <section className="app-surface p-3"><form onSubmit={applySearch} className="grid gap-3 lg:grid-cols-[1fr_15rem_auto]"><div className="relative"><label className="sr-only" htmlFor="inspectionSearch">Search inspections</label><Search size={16} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" /><input id="inspectionSearch" className="ui-input pl-10" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Search inspection ID, product, or brand" /></div><div className="relative"><Filter size={15} className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" /><label className="sr-only" htmlFor="complianceFilter">Filter by compliance status</label><select id="complianceFilter" className="ui-select pl-9" value={complianceStatus} onChange={(event) => { setPage(1); setComplianceStatus(event.target.value); }}><option value="">All compliance states</option><option value="PASS">Compliant</option><option value="FAIL">Non-compliant</option><option value="REVIEW">Needs review</option><option value="NOT_ANALYSED">Not analysed</option></select></div><button className="ui-button-secondary" type="submit">Apply filters</button></form></section>
    {failed && <Alert tone="error">The inspection register could not be loaded. Check the API connection and try again.</Alert>}
    {loading ? <LoadingState label="Loading inspection register" /> : inspections.length === 0 ? <EmptyState icon={<ClipboardList size={30} />} title={appliedSearch || complianceStatus ? 'No matching inspections' : 'No inspections created'} description={appliedSearch || complianceStatus ? 'Try clearing a filter or adjusting the search phrase.' : 'Open your first evidence record to begin compliance analysis.'} action={!appliedSearch && !complianceStatus ? <Link to="/inspections/new" className="ui-button-primary">Create inspection</Link> : undefined} /> : <>
      <section className="app-surface hidden overflow-hidden md:block"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="border-b border-[var(--line)] bg-[#0a0f18] text-[10px] font-bold uppercase tracking-[.12em] text-[var(--text-faint)]"><tr><th className="px-5 py-3">Inspection</th><th className="px-5 py-3">Product</th><th className="px-5 py-3">Evidence</th><th className="px-5 py-3">Lifecycle</th><th className="px-5 py-3">Compliance</th><th className="px-5 py-3">Created</th><th className="w-10" /></tr></thead><tbody className="divide-y divide-[var(--line)]">{inspections.map((inspection) => <tr key={inspection.id} className="transition-colors hover:bg-[var(--surface-raised)]"><td className="px-5 py-4"><Link to={`/inspections/${inspection.id}`} className="font-mono text-xs font-bold text-[#a9c7ff] hover:text-white">{inspection.inspection_number}</Link></td><td className="px-5 py-4"><p className="text-sm font-medium text-[var(--text)]">{inspection.product_name}</p><p className="mt-1 text-xs text-[var(--text-faint)]">{inspection.brand}</p></td><td className="px-5 py-4"><span className="inline-flex items-center gap-1.5 font-mono text-xs text-[var(--text-muted)]"><ImageIcon size={14} />{inspection.image_count}</span></td><td className="px-5 py-4"><StatusBadge value={inspection.status} /></td><td className="px-5 py-4"><StatusBadge value={inspection.compliance_status} /></td><td className="px-5 py-4 font-mono text-xs text-[var(--text-muted)]">{new Date(inspection.created_at).toLocaleDateString()}</td><td className="px-4 py-4"><Link to={`/inspections/${inspection.id}`} className="ui-icon-button" aria-label={`Open ${inspection.inspection_number}`}><ArrowRight size={16} /></Link></td></tr>)}</tbody></table></div></section>
      <section className="space-y-3 md:hidden">{inspections.map((inspection) => <Link key={inspection.id} to={`/inspections/${inspection.id}`} className="app-card app-card-interactive block p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="font-mono text-xs font-bold text-[#a9c7ff]">{inspection.inspection_number}</p><p className="mt-2 truncate text-sm font-semibold text-[var(--text)]">{inspection.product_name}</p><p className="mt-1 text-xs text-[var(--text-faint)]">{inspection.brand}</p></div><ArrowRight size={17} className="shrink-0 text-[var(--text-faint)]" /></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge value={inspection.status} /><StatusBadge value={inspection.compliance_status} /><span className="inline-flex items-center gap-1 text-xs text-[var(--text-muted)]"><ImageIcon size={13} />{inspection.image_count}</span></div></Link>)}</section>
    </>}
    {pages > 1 && <div className="flex items-center justify-between"><p className="font-mono text-xs text-[var(--text-faint)]">Page {page} of {pages}</p><div className="flex gap-2"><button className="ui-icon-button" onClick={() => setPage((current) => Math.max(1, current - 1))} disabled={page === 1} aria-label="Previous page"><ChevronLeft size={17} /></button><button className="ui-icon-button" onClick={() => setPage((current) => Math.min(pages, current + 1))} disabled={page === pages} aria-label="Next page"><ChevronRight size={17} /></button></div></div>}
  </div>;
}
