import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertCircle, ArrowLeft, ArrowRight, Loader2, Package, Tag } from 'lucide-react';
import { createInspection } from '../api/inspections';
import { ProgressStages } from '../components/ui';

export default function NewInspectionPage() {
  const [productName, setProductName] = useState(''); const [brand, setBrand] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setLoading(true); try { const inspection = await createInspection({ product_name: productName, brand }); navigate(`/inspections/${inspection.id}`); } catch (err: any) { setError(err?.response?.data?.error?.message || 'The inspection could not be created. Please try again.'); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-3xl space-y-7"><button className="inline-flex items-center gap-1.5 text-sm text-[var(--text-muted)] hover:text-[var(--brand-hover)]" onClick={() => navigate('/inspections')}><ArrowLeft size={16} /> Back to register</button><header><p className="app-kicker">Step 1 of 3 · Case intake</p><h2 className="app-title mt-2">Open an evidence record.</h2><p className="app-subtitle mt-3">Record the packaged product first. Evidence and compliance analysis continue in the inspection workspace.</p></header><section className="app-surface overflow-hidden"><div className="border-b border-[var(--line)] px-5 py-5 sm:px-7"><ProgressStages stages={['Case details', 'Evidence', 'Analysis & decision']} activeIndex={0} /></div><div className="p-5 sm:p-7">{error && <div className="ui-alert ui-alert-error mb-6" role="alert"><AlertCircle size={17} />{error}</div>}<div className="mb-6"><p className="app-kicker">Case details</p><h3 className="section-title mt-2">Product identification</h3><p className="mt-1 text-sm text-[var(--text-muted)]">Use the declaration printed on the product package wherever possible.</p></div><form className="space-y-6" onSubmit={submit}><div><label className="ui-label" htmlFor="productName">Product name</label><div className="relative"><Package className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" size={17} /><input className="ui-input pl-10" id="productName" value={productName} onChange={(event) => setProductName(event.target.value)} required placeholder="e.g. Packaged Basmati Rice, 5 kg" /></div><p className="ui-field-hint">This label identifies the inspection throughout the workspace.</p></div><div><label className="ui-label" htmlFor="brand">Brand</label><div className="relative"><Tag className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-faint)]" size={17} /><input className="ui-input pl-10" id="brand" value={brand} onChange={(event) => setBrand(event.target.value)} required placeholder="e.g. India Gate" /></div></div><div className="flex flex-col-reverse gap-3 border-t border-[var(--line)] pt-6 sm:flex-row sm:justify-end"><button type="button" className="ui-button-secondary" onClick={() => navigate('/inspections')}>Cancel</button><button className="ui-button-primary" type="submit" disabled={loading}>{loading ? <><Loader2 size={16} className="animate-spin" /> Creating record…</> : <>Continue to evidence <ArrowRight size={16} /></>}</button></div></form></div></section></div>;
}
