"""Phase 4: Add compliance report tables

Revision ID: c8ec16622252
Revises: 003_product_info
Create Date: 2026-08-27 22:00:03.245160
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8ec16622252'
down_revision: Union[str, None] = '003_product_info'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocr_result_id', sa.UUID(), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=False),
    sa.Column('total_rules_checked', sa.Integer(), nullable=False),
    sa.Column('passed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('not_applicable_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_reports_ocr_result_id'), 'compliance_reports', ['ocr_result_id'], unique=True)
    op.create_table('compliance_rule_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=True),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['compliance_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rule_results_report_id'), 'compliance_rule_results', ['report_id'], unique=False)
    op.drop_constraint('inspections_inspection_number_key', 'inspections', type_='unique')
    op.drop_index('ix_inspections_inspection_number', table_name='inspections')
    op.create_index(op.f('ix_inspections_inspection_number'), 'inspections', ['inspection_number'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_inspections_inspection_number'), table_name='inspections')
    op.create_index('ix_inspections_inspection_number', 'inspections', ['inspection_number'], unique=False)
    op.create_unique_constraint('inspections_inspection_number_key', 'inspections', ['inspection_number'])
    op.drop_index(op.f('ix_compliance_rule_results_report_id'), table_name='compliance_rule_results')
    op.drop_table('compliance_rule_results')
    op.drop_index(op.f('ix_compliance_reports_ocr_result_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    # ### end Alembic commands ###
